name: prerelease NuGet

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # also works with windows-latest and macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Checkout models directory
      run: cd AdvertApi.Models
      shell: bash
    - name: Build with dotnet
      run: dotnet build --configuration Release --version-suffix prerelease-$(date +%Y%m%d%H%M%S)
      shell: bash
    - name: Checkout main directory
      run: cd ..
      shell: bash
    - name: Publish nuget
      run: |
           for f in ./WebAdvert.AdvertApi/AdvertApi.Models/bin/Release/*.nupkg
           do
             curl -vX PUT -u "johnkuan:${{ secrets.GHPackagesToken }}" -F package=@$f https://nuget.pkg.github.com/johnkuan/
           done
      shell: bash
